.PHONY: clean All

All:
	@echo "----------Building project:[ ZybooksOutputTester - Debug ]----------"
	@cd "/Users/JonathanWesterfield/Documents/CSCE 121/ZybooksOutputTester" && "$(MAKE)" -f  "ZybooksOutputTester.mk"
clean:
	@echo "----------Cleaning project:[ ZybooksOutputTester - Debug ]----------"
	@cd "/Users/JonathanWesterfield/Documents/CSCE 121/ZybooksOutputTester" && "$(MAKE)" -f  "ZybooksOutputTester.mk" clean
