.PHONY: clean All

All:
	@echo "----------Building project:[ Palindromes - Debug ]----------"
	@cd "/Users/JonathanWesterfield/Documents/CSCE 121/Palindromes" && "$(MAKE)" -f  "Palindromes.mk"
clean:
	@echo "----------Cleaning project:[ Palindromes - Debug ]----------"
	@cd "/Users/JonathanWesterfield/Documents/CSCE 121/Palindromes" && "$(MAKE)" -f  "Palindromes.mk" clean
